# Generated by Django 5.0.6 on 2024-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, default='')),
                ('date', models.DateField()),
                ('excerpt', models.TextField(max_length=200)),
                ('content', models.TextField(max_length=20000)),
            ],
        ),
    ]
