# Generated by Django 5.0.6 on 2024-06-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
